In [1]:
import pandas as pd
import numpy as np

In [2]:
initial_data = pd.read_csv('data.csv')
PRIZ=10
SIZ=2

In [3]:
initial_data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
initial_data.drop(initial_data.columns[0], axis=1, inplace=True)

In [5]:
for column in initial_data.columns:
    if "mean" not in column:
        if 'diagnosis' not in column:
            initial_data.drop(column, axis = 1, inplace=True)

In [6]:
initial_data['diagnosis']=initial_data['diagnosis'].map({'M':1,'B':0})

In [24]:
rez = initial_data.mean().values

In [31]:
for i,column in enumerate(initial_data.columns):
        r=rez[i]
        initial_data[column]=initial_data[column].apply(lambda x: 1 if x >r else 0)

diagnosis
radius_mean
texture_mean
perimeter_mean
area_mean
smoothness_mean
compactness_mean
concavity_mean
concave points_mean
symmetry_mean
fractal_dimension_mean

In [32]:
initial_data

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,1,1,0,1,1,1,1,1,1,1,1
1,1,1,0,1,1,0,0,0,1,1,0
2,1,1,1,1,1,1,1,1,1,1,0
3,1,0,1,0,0,1,1,1,1,1,1
4,1,1,0,1,1,1,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
564,1,1,1,1,1,1,1,1,1,0,0
565,1,1,1,1,1,1,0,1,1,0,0
566,1,1,1,1,1,0,0,1,1,0,0
567,1,1,1,1,1,1,1,1,1,1,1
568,0,0,1,0,0,0,0,0,0,0,0

In [33]:
dfM=initial_data[initial_data['diagnosis']==1]
dfM.drop('diagnosis', axis = 1, inplace=True)
dfB=initial_data[initial_data['diagnosis']==0]
dfB.drop('diagnosis', axis = 1, inplace=True)

/home/varvara/snap/jupyter/common/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [34]:
m_m=len(dfM)

In [35]:
m_b=len(dfB)

In [36]:
B=np.zeros( (SIZ, PRIZ) )

In [37]:
def countB(N,M,df):
    for i in range(PRIZ):
        B[N][i]=sumX(M,df.values,i)/M        
def sumX(M,x,t):
    s=0
    for j in range(M):
        s+=x[j][t]
    return s    
        
countB(0,m_m,dfM)        
countB(1,m_b,dfB)

In [38]:
B

array([[0.8490566 , 0.75471698, 0.85849057, 0.80660377, 0.68396226,
        0.79245283, 0.86792453, 0.91509434, 0.63207547, 0.41981132],
       [0.12885154, 0.28851541, 0.1232493 , 0.09243697, 0.37815126,
        0.21008403, 0.10644258, 0.08963585, 0.36414566, 0.42577031]])

In [39]:
BT=np.zeros(PRIZ)
A=np.zeros( (SIZ, PRIZ) )

In [40]:
for i in range(PRIZ):
    s=0
    for j in range(SIZ):
        s+=B[j][i]
    BT[i]=s/SIZ
for i in range(PRIZ):
    for j in range(SIZ):
        A[j][i]=abs(B[j][i]-BT[i])

In [41]:
mat = np.matrix(A)
with open('outfile.txt','wb') as f:
    for line in mat:
        np.savetxt(f, line, fmt='%.5f')

In [42]:
for i,j in enumerate(BT):
    print(j)

0.4889540721949157
0.5216161936472703
0.4908699328788119
0.4495203741874108
0.5310567623275726
0.5012684319010623
0.48718355266634955
0.5023650969821891
0.49811056498070927
0.42279081443898314